
--------------------POPC------------------
~bend_parm[\atom1{NC}\atom2{PH}\atom3{GL}\pot_type{harm}\fk{1559.517}\eq{112.0}]
~bend_parm[\atom1{PH}\atom2{GL}\atom3{EST1}\pot_type{harm}\fk{704.298}\eq{124.0}]
~bend_parm[\atom1{PH}\atom2{GL}\atom3{EST2}\pot_type{harm}\fk{1006.14}\eq{138.0}]
~bend_parm[\atom1{GL}\atom2{EST1}\atom3{CM}\pot_type{harm}\fk{402.456}\eq{168.0}]
~bend_parm[\atom1{GL}\atom2{EST2}\atom3{CM}\pot_type{harm}\fk{402.456}\eq{172.0}]
~bend_parm[\atom1{EST1}\atom2{GL}\atom3{EST2}\pot_type{harm}\fk{503.07}\eq{95.0}]
~bend_parm[\atom1{EST1}\atom2{CM}\atom3{CM}\pot_type{harm}\fk{503.07}\eq{178.0}]
~bend_parm[\atom1{EST2}\atom2{CM}\atom3{CM}\pot_type{harm}\fk{503.07}\eq{178.0}]
~bend_parm[\atom1{NH}\atom2{PHE}\atom3{GL}\pot_type{harm}\fk{2012.28}\eq{102.0}]
~bend_parm[\atom1{CM}\atom2{CM}\atom3{CM}\pot_type{harm}\fk{598.6533}\eq{173.0}]
~bend_parm[\atom1{CM}\atom2{CM}\atom3{CT}\pot_type{harm}\fk{598.6533}\eq{175.0}]
~bend_parm[\atom1{CT2}\atom2{CM}\atom3{CM}\pot_type{harm}\fk{804.912}\eq{172.0}]
~bend_parm[\atom1{CT2}\atom2{CM}\atom3{CT}\pot_type{harm}\fk{804.912}\eq{172.0}]
~bend_parm[\atom1{CT2}\atom2{CM}\atom3{CT2}\pot_type{harm}\fk{855.219}\eq{173.0}]
~bend_parm[\atom1{CT}\atom2{CM}\atom3{CT}\pot_type{harm}\fk{549.85551}\eq{175.5}]
~bend_parm[\atom1{CMD2}\atom2{CM}\atom3{CM}\pot_type{harm}\fk{955.833}\eq{161.0}]
~bend_parm[\atom1{CM}\atom2{CMD2}\atom3{CM}\pot_type{harm}\fk{3018.42}\eq{110.0}]
    ------------Harmonic bend ---------------

~bend_parm[\atom1{GBH}\atom2{GBH}\atom3{SER}\pot_type{harm}\fk{3445.1}\eq{87.7}\label{nside}]

~bend_parm[\atom1{SER}\atom2{GBH}\atom3{GBH}\pot_type{quartic}
\eq{0}\fk{0}\a0{33044.7}\a1{-60686.3}\a2{43230.0}\a3{-13519.3}\a4{1561.4}\label{cside}]
   
   --------------Quartic Bends -----------------
~bend_parm[\atom1{GBB}\atom2{ABB}\atom3{GBB}\pot_type{quartic}
\eq{0}\fk{0}\a0{41614.4}\a1{-81997.7}\a2{60408.6}\a3{-19161.2}\a4{2221.9}]

~bend_parm[\atom1{GBH}\atom2{GBH}\atom3{GBH}\pot_type{quartic}
\eq{0}\fk{0}\a0{41278.9}\a1{-78009.4}\a2{55663.9}\a3{-17263.1}\a4{1972.7}]
~bend_parm[\atom1{GBH}\atom2{GBH}\atom3{LEU}\pot_type{quartic}
\eq{0}\fk{0}\a0{25440.7}\a1{-55617.0}\a2{47133.4}\a3{-17509.5}\a4{2416.1}\label{nside}]
~bend_parm[\atom1{LEU}\atom2{GBH}\atom3{GBH}\pot_type{quartic}
\eq{0}\fk{0}\a0{39625.6}\a1{-73757.4}\a2{52572.6}\a3{-16398.5}\a4{1887.2}\label{cside}]
